# Generated by Django 4.2.11 on 2024-09-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image_description', models.TextField(blank=True)),
                ('content', models.TextField(max_length=250)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
    ]
